/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package loderunner.ui;

import javax.swing.*;
import java.awt.*;

import loderunner.utils.*;
import loderunner.model.*;

/**
 *
 * @author Mohamed Kazaliou Bah
 */
// une partie de cette classe a été déclarée sur netbeans
public class GamePanel extends JPanel {
    private Plateau plateau;
    private static final int TILE_SIZE = 32;
    private long tick_moteur = 0; // variable qui sera modifiable que par le moteur pour aider avec l'animation
                                  // des entites

    /**
     * Creates new form GamePanel
     */

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 400, Short.MAX_VALUE));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 300, Short.MAX_VALUE));
    }// </editor-fold>//GEN-END:initComponents

    @Override
    protected void paintComponent(Graphics g0) {
        Graphics2D g = (Graphics2D) g0;
        super.paintComponent(g);
        double scaleX = (double) getWidth() / (plateau.getLargeur() * TILE_SIZE);
        double scaleY = (double) getHeight() / (plateau.getHauteur() * TILE_SIZE);

        // On choisit le plus petit des deux pour garder les proportions
        double scale = Math.min(scaleX, scaleY);

        g.scale(scale, scale);
        dessinerPlateau(g);
        dessinerEntites(g);
        dessinerInterface(g);
    }

    public GamePanel(Plateau p) {
        this.plateau = p;
        initComponents();
        // 1. Calcul de la taille basée sur le modèle (Largeur x Hauteur du plateau)
        int largeurPx = plateau.getLargeur() * TILE_SIZE;
        int hauteurPx = plateau.getHauteur() * TILE_SIZE;
        Dimension dimensionJeu = new Dimension(largeurPx, hauteurPx);

        // 2. Configuration de la fenêtre (Fixe et précise)
        this.setPreferredSize(dimensionJeu);
        this.setMinimumSize(dimensionJeu);
        this.setMaximumSize(dimensionJeu);

        // 3. Optimisations graphiques
        this.setBackground(new Color(173, 216, 230)); // Le bleu ciel par défaut
        this.setDoubleBuffered(true); // Élimine les scintillements

        // 4. Préparation des entrées (Clavier)
        this.setFocusable(true);
        this.requestFocusInWindow();

    }

    public void setPlateau(Plateau p) {
        this.plateau = p;
        this.tick_moteur = 0;
    }

    public void incrementerTick() {
        this.tick_moteur++;
    }

    public long getTick() {
        return this.tick_moteur;
    }

    private void dessinerPlateau(Graphics g) {
        Color Background = new Color(173, 216, 230);
        for (int y = 0; y < this.plateau.getHauteur(); y++) {
            for (int x = 0; x < this.plateau.getLargeur(); x++) {
                Case type = plateau.getCase(x, y);
                int posX = x * TILE_SIZE;
                int posY = y * TILE_SIZE;
                switch (type) {
                    case MUR:
                        g.drawImage(ImageLoader.getImage("Environnement/mur.png"), posX, posY,
                                TILE_SIZE, TILE_SIZE,
                                null);
                        break;

                    case ECHELLE:
                        g.drawImage(ImageLoader.getImage("Environnement/echelle.png"), posX, posY, TILE_SIZE, TILE_SIZE,
                                null);
                        break;
                    case TROU:
                        g.setColor(Background);
                        g.fillRect(posX, posY, TILE_SIZE, TILE_SIZE);
                        g.drawImage(ImageLoader.getImage("Environnement/trou.png"), posX, posY, TILE_SIZE, TILE_SIZE,
                                null);
                        break;
                    case LINGOT:
                        g.setColor(Background);
                        g.fillRect(posX, posY, TILE_SIZE, TILE_SIZE);
                        g.drawImage(ImageLoader.getImage("Environnement/lingot.png"), posX, posY, TILE_SIZE, TILE_SIZE,
                                null);
                        break;
                    case PASSERELLE:
                        g.setColor(Background);
                        g.fillRect(posX, posY, TILE_SIZE, TILE_SIZE);
                        g.drawImage(ImageLoader.getImage("Environnement/passerelle.png"), posX, posY, TILE_SIZE,
                                TILE_SIZE,
                                null);
                        break;
                    case SORTIE:
                    default:
                        g.setColor(Background);
                        g.fillRect(posX, posY, TILE_SIZE, TILE_SIZE);
                        break;
                }
            }
        }
    }

    private void dessinerEntites(Graphics g) {
        for (Joueur j : plateau.getJoueurs()) {
            animate(j, g, false);
        }
        for (Garde garde : plateau.getGardes()) {
            animate(garde, g, true);
        }
    }

    // méthode qui anime les entites
    private void animate(Entite e, Graphics g, boolean estGarde) {
        long tick = this.getTick();
        Direction dir = e.getDirection();
        int frame = (int) (tick / 8) % 2;

        String imgPath;
        if (estGarde) {
            if (dir == Direction.AUCUNE) {
                imgPath = "Gardes/AUCUNE.png";
            } else {
                imgPath = "Gardes/" + dir + "_" + frame + ".png";
            }
        } else {
            // Pour le joueur, AUCUNE n'existe qu'en frame 0
            int frameJoueur = (dir == Direction.AUCUNE) ? 0 : frame;
            imgPath = "Joueur/" + dir + "_" + frameJoueur + ".png";
        }

        g.drawImage(ImageLoader.getImage(imgPath), e.getX() * TILE_SIZE, e.getY() * TILE_SIZE, null);
    }

    private void dessinerInterface(Graphics g) {
        if (plateau.getJoueurs().isEmpty()) return;
        Joueur joueur = plateau.getJoueurs().get(0);

        int largeurPx = plateau.getLargeur() * TILE_SIZE;
        int hauteurPx = plateau.getHauteur() * TILE_SIZE;

        // Bandeau semi-transparent sur la bordure haute
        g.setColor(new Color(0, 0, 0, 150));
        g.fillRect(0, 0, largeurPx, TILE_SIZE);

        // Score à gauche
        g.setColor(Color.WHITE);
        g.setFont(new Font("Arial", Font.BOLD, 18));
        g.drawString("SCORE : " + joueur.getScore(), 8, 22);

        // Vies à droite sous forme de coeurs
        Image coeur = ImageLoader.getImage("Environnement/heart.png");
        int vies = joueur.getVies();
        for (int i = 0; i < vies; i++) {
            int posX = largeurPx - (i + 1) * (TILE_SIZE + 2);
            g.drawImage(coeur, posX, 4, TILE_SIZE, TILE_SIZE - 8, null);
        }

        // Écran Victoire
        if (plateau.isPartieGagnee()) {
            g.setColor(new Color(0, 0, 0, 170));
            g.fillRect(0, 0, largeurPx, hauteurPx);

            g.setColor(Color.YELLOW);
            g.setFont(new Font("Arial", Font.BOLD, 48));
            String texte = "YOU WIN !";
            FontMetrics fm = g.getFontMetrics();
            int x = (largeurPx - fm.stringWidth(texte)) / 2;
            int y = hauteurPx / 2 - 10;
            g.drawString(texte, x, y);

            g.setColor(Color.WHITE);
            g.setFont(new Font("Arial", Font.PLAIN, 20));
            String score = "Score final : " + joueur.getScore();
            fm = g.getFontMetrics();
            g.drawString(score, (largeurPx - fm.stringWidth(score)) / 2, y + 40);
            return;
        }

        // Écran Game Over
        if (joueur.estMort()) {
            g.setColor(new Color(0, 0, 0, 170));
            g.fillRect(0, 0, largeurPx, hauteurPx);

            g.setColor(Color.RED);
            g.setFont(new Font("Arial", Font.BOLD, 48));
            String texte = "GAME OVER";
            FontMetrics fm = g.getFontMetrics();
            int x = (largeurPx - fm.stringWidth(texte)) / 2;
            int y = hauteurPx / 2 - 10;
            g.drawString(texte, x, y);

            g.setColor(Color.WHITE);
            g.setFont(new Font("Arial", Font.PLAIN, 20));
            String score = "Score final : " + joueur.getScore();
            fm = g.getFontMetrics();
            g.drawString(score, (largeurPx - fm.stringWidth(score)) / 2, y + 40);
        }
    }
}
