/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package loderunner.ui;
import javax.swing.*;
import java.awt.*;
import loderunner.utils.*;
import loderunner.model.*;

/**
 *
 * @author Mohamed Kazaliou Bah
 */
public class GamePanel extends JPanel {
    private Plateau plateau;
    private static final int TILE_SIZE=32;
    /**
     * Creates new form GamePanel
     */
    public GamePanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
    @Override
    public void paintComponents(Graphics g){
        super.paintComponent(g);
        dessinerPlateau(g);
        dessinerItems(g);
        dessinerEntites(g);
        dessinerInterface(g);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

    private void dessinerPlateau(Graphics g) {
        for(int x=0; x<this.plateau.gethauteur(); x++){
            for(int y=0; y<this.plateau.getLargeur(); y++){
                Case type=plateau.getCase(x, y);
                int posX=x*TILE_SIZE;
                int posY=y*TILE_SIZE;
                switch (type) {
                    case MUR:
                        
                        break;
                
                    default:
                        break;
                }
            }
        }
    }

    private void dessinerItems(Graphics g) {
    }

    private void dessinerEntites(Graphics g) {
    }

    private void dessinerInterface(Graphics g) {

    }
}
